### ISSUE TITLE
Error when a database name use / or %2F

### ISSUE THREAD

**Issue by fredericalix** [neighbourhoodie/couch-continuum#32] opened 2018-05-30 07:48 UTC
I can't use couch-continuum with a database name like this toto/test2-io

```
couch-continuum -n "toto/test2-io" -q 1 -v
[couch-continuum] Created new continuum: {"db1":"toto%2Ftest2-io","db2":"toto%2Ftest2-io_temp_copy","interval":1000,"q":1}
[couch-continuum] Migrating database 'toto/test2-io'...
[couch-continuum] Creating replica toto%2Ftest2-io_temp_copy...
[couch-continuum] [0/5] Checking if primary is in use...
[couch-continuum] [1/5] Creating replica db: toto%2Ftest2-io_temp_copy
[couch-continuum] [2/5] Beginning replication of primary to replica...
[couch-continuum] Replicating toto%2Ftest2-io to toto%2Ftest2-io_temp_copy
[couch-continuum] (                    ) 0% 0.0s[couch-continuum] ERROR
[couch-continuum] Unexpected error: {"error":"db_not_found","reason":"could not open http://localhost:5984/toto%252Ftest2-io/"}
```

**Comment by garbados** [comment] 2018-06-13 18:05
It looks like the URL is getting double-encoded (`%2F` -> `%252F`), but I'm unable to reproduce the issue locally. Still trying...

**Comment by garbados** [comment] 2018-06-13 18:07
What version of couch-continuum are you using?

**Comment by garbados** [comment] 2018-10-03 22:11
Checking in on this issue -- it's been a few versions since you filed it. I'm going to close it for now, but I'll re-open it if you're still experiencing the problem.

**Closed by garbados** 2018-10-03 22:11 UTC
